# Site settings
# baseurl = "https://datatonanticorrupcion.mx/"
relativeURLs = true
languageCode = "es-mx"
defaultContentLanguage = "es"
title = "Datatón Anticorrupción"
theme = "dataton-agency"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines
  name = "Datatón Anticorrupción 2021"
  description = """El datatón anticorrupción es una iniciativa donde construiremos herramientas 
  que analicen datos abiertos con el fin de combatir la corrupción en México."""
  twitter_user = "@SESNAOficial"
  images = [""]
  start_date = "2021-12-02T17:00-05:00"
  end_date = "2021-12-05T16:00-05:00"
  logo = "/img/logo-navbar.svg"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "/favicon.ico"

  # 404 error customization
  [params.error404]
    heading = "No se encontró esa página"
    text = "Por favor visita [esta página](/)"

  # Navigation
  [params.navigation]
    brand = "Datatón Anticorrupción"
    # Optional logo as brand stored in img/
    logo = "logo-navbar.svg"
 
    [[menu.main]]
      name = "Convocatoria"
      url = "/#info"
      weight = 1

    [[menu.main]]
      name = "Contexto"
      url = "/contexto"
      weight = 4

    [[menu.main]]
      url = "/preguntas-frecuentes"
      name = "Dudas"
      weight = 9

  [params.navigation_button]
    link = "/participa"
    label = "Participa"      

  # Sección de hero en homepage. 
  [params.hero]
  # Dado que el layout es muy particular para este evento, el contenido está 
  # hardcoded en layouts/partials/hero.html

  # Sección de información clave
  [params.info]
    enable = true

  [params.faq]
    enable = true

  # Mentores
  [params.mentores]
    enable = true

  # Jueces
  [params.jueces]
    enable = true

  # Sponsors section
  # Los logos de los aliados están en 'static/img/logos'.
  # El tamaño ideal es 280px*80px
    [params.sponsors]
      enable = true
      center = true

    [params.sponsors1_list]
      enable = true
      title = "Patrocinado por"

      [[params.sponsors1]]
        logo = "usaid.png"
        link = "https://www.usaid.gov/es/mexico"

    [params.sponsors2_list]
      
      enable = true
      title = "Una iniciativa de " 

      [[params.sponsors2]]
        logo = "PDN_plataforma.png"
        link = "https://plataformadigitalnacional.org"

      [[params.sponsors2]]
        logo = "sesna.png"
        link = "https://www.gob.mx/sesna"

    [params.sponsors3_list]
      enable = true
      title = "Con el apoyo de" 


      [[params.sponsors3]]
        logo = "amazon.png"
        link = "https://www.amazon.com.mx"

      [[params.sponsors3]]
        logo = "caf2.png"
        link = "https://www.caf.com"

      [[params.sponsors3]]
        logo = "imco.png"
        link = "https://imco.org.mx/"

      [[params.sponsors3]]
        logo = "HACIENDA.png"
        link = "https://www.gob.mx/pff"


    [params.sponsors4_list]
      enable = true
      title = "Producido por"

      [[params.sponsors4]]
        logo = "sg.png"
        link = "https://sg.com.mx"

      
  # Footer section
  [params.footer]
    enable = true
    leyenda = "La realización del datatón anticorrupción es posible gracias al apoyo del pueblo de de los Estados Unidos a través de la Agencia de los Estados Unidos para el desarrollo Internacional (USAID). El evento es responsabilidad de los organizadores y no refleja necesariamente el punto de vista de USAID o del gobierno de los Estados Unidos de América."
    copyright = "Otro fantástico evento de <a href='https://sg.com.mx'>SG</a>."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/SESNAOficial"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/SESNAOficial"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-envelope-o"
      link = "mailto:dataton@sg.com.mx"
      title = "Correo electrónico"

    [[params.footer.quicklinks]]
      text = "Código de Conducta"
      link = "/coc"

    [[params.footer.quicklinks]]
      text = "Privacidad de datos"
      link = "/privacidad"

